In [1]:
import numpy as np
import pandas as pd

In [2]:
url ='https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?file=data/isoc_cimobi_frq.tsv.gz&unzip=true'

In [4]:
df=pd.read_csv(url, delimiter = '\t')

In [5]:
df.head()

,"indic_is,ind_type,unit,time\geo",EU27_2020,EU28,EU27_2007,EU15,EA,BE,BG,CZ,DK,...,SI,SK,FI,SE,IS,NO,UK,ME,MK,TR
0,"I_IHDDAY,CB_EU_FOR,PC_IND,2012",13,15,15,16,12,15,: u,: u,22,...,: u,14 u,35 u,35 u,16,31 u,39,:,:,:
1,"I_IHDDAY,CB_EU_FOR,PC_IND_IU3,2012",18,21,21,21,17,19,: u,: u,22,...,: u,17 u,36 u,40 u,17,32 u,46 u,:,:,:
2,"I_IHDDAY,CB_EU_FOR,PC_IND_IUHD,2012",57,57,57,57,55,48,: u,: u,49 u,...,: u,: u,: u,: u,40 u,50 u,60 u,:,:,:
3,"I_IHDDAY,CB_EXT_EU,PC_IND,2012",15,21,21,22,13,11,25 u,:,35,...,3,: u,22,39,16 u,32 u,39,:,:,:
4,"I_IHDDAY,CB_EXT_EU,PC_IND_IU3,2012",21,28,28,29,19,15,28 u,:,39,...,5,: u,24 u,42,17 u,32 u,43,:,:,:

In [7]:
df_desc=df['indic_is,ind_type,unit,time\\geo'].str.split(',', expand=True)

In [10]:
df_desc.rename({0:'indic_is',1:'ind_type',2:'unit',3:'time'},axis=1, inplace=True)

In [11]:
df_desc.join(df)

,indic_is,ind_type,unit,time,"indic_is,ind_type,unit,time\geo",EU27_2020,EU28,EU27_2007,EU15,EA,...,SI,SK,FI,SE,IS,NO,UK,ME,MK,TR
0,I_IHDDAY,CB_EU_FOR,PC_IND,2012,"I_IHDDAY,CB_EU_FOR,PC_IND,2012",13,15,15,16,12,...,: u,14 u,35 u,35 u,16,31 u,39,:,:,:
1,I_IHDDAY,CB_EU_FOR,PC_IND_IU3,2012,"I_IHDDAY,CB_EU_FOR,PC_IND_IU3,2012",18,21,21,21,17,...,: u,17 u,36 u,40 u,17,32 u,46 u,:,:,:
2,I_IHDDAY,CB_EU_FOR,PC_IND_IUHD,2012,"I_IHDDAY,CB_EU_FOR,PC_IND_IUHD,2012",57,57,57,57,55,...,: u,: u,: u,: u,40 u,50 u,60 u,:,:,:
3,I_IHDDAY,CB_EXT_EU,PC_IND,2012,"I_IHDDAY,CB_EXT_EU,PC_IND,2012",15,21,21,22,13,...,3,: u,22,39,16 u,32 u,39,:,:,:
4,I_IHDDAY,CB_EXT_EU,PC_IND_IU3,2012,"I_IHDDAY,CB_EXT_EU,PC_IND_IU3,2012",21,28,28,29,19,...,5,: u,24 u,42,17 u,32 u,43,:,:,:
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
442,I_IHDLTWK,Y75_MAX,PC_IND_IU3,2012,"I_IHDLTWK,Y75_MAX,PC_IND_IU3,2012",:,:,:,:,:,...,:,: u,:,:,:,15 u,5,:,:,:
443,I_IHDLTWK,Y75_MAX,PC_IND_IUHD,2012,"I_IHDLTWK,Y75_MAX,PC_IND_IUHD,2012",:,:,:,:,:,...,:,:,:,:,:,: u,: u,:,:,:
444,I_IHDUSE,CB_EU_FOR,PC_IND,2012,"I_IHDUSE,CB_EU_FOR,PC_IND,2012",19,22,22,22,18,...,: u,18 u,45 u,43 u,29,49 u,56,:,:,:
445,I_IHDUSE,CB_EU_FOR,PC_IND_IU3,2012,"I_IHDUSE,CB_EU_FOR,PC_IND_IU3,2012",26,30,30,30,25,...,: u,22 u,47 u,48 u,30,51 u,67 u,:,:,:
446,I_IHDUSE,CB_EU_FOR,PC_IND_IUHD,2012,"I_IHDUSE,CB_EU_FOR,PC_IND_IUHD,2012",81,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df_desc.drop('indic_is,ind_type,unit,time\\geo', axis=1)

KeyError: "['indic_is,ind_type,unit,time\\\\geo'] not found in axis"

In [17]:
plik_json = 'https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?file=data/isoc_cimobi_frq.tsv.gz&unzip=true'

In [21]:
pd.read_json(plik_json)

ValueError: Expected object or value